# #usersignup
# POST http://localhost:3001/v1/user
# Content-Type: application/json

# {
# "name":"konami",
# "company":"facebook",
# "address":"usa",
# "phone":"745908",
# "email":"ja4jslsa4@gmail.com",
# "password":"majicpot"
# }



//usersignup
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
"email":"jacksongeorge1998@gmail.com",
"password":"majicpot"
}


# GET  http://localhost:3001/v1/user
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphY2tzb25AZ21haWwuY29tIiwiaWF0IjoxNjYzMjI2MDA4LCJleHAiOjE2NjMyMjY5MDh9.My61GQQ5L23TgJpJiwWdmeB9OHrIY3Fn4WUVomcMA3M





